version: '3.8'

services:
  app:
    build: .
    container_name: spring_app
    environment:
#      SPRING_DATASOURCE_URL:
#      SPRING_DATASOURCE_USERNAME:
#      SPRING_DATASOURCE_PASSWORD:
#      SPRING_JPA_HIBERNATE_DDL_AUTO:
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_FOX_DOCUMENTATION_SWAGGER_UI_ENABLE: true
    ports:
      - "8080:8080"
volumes:
  postgres_data: